/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instalaciones.ui;

import static instalaciones.ui.Funciones.*;
import instalaciones.util.HibernateUtil;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author jcalzado
 */
public class Home extends javax.swing.JFrame {

    static Session sesion = HibernateUtil.getSessionFactory().openSession();
    static Date fechaActual = new Date();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void txtListarInstalacionesNombreActionPerformed (ActionEvent evt) {}
    public void txtListarInstalacionesPoblacionActionPerformed(ActionEvent evt) {}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpUsuario = new javax.swing.JFrame();
        btnPopUpUsuarioEjecutar = new javax.swing.JButton();
        btnCancelarUsuario = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtPopUpUsuarioDni = new javax.swing.JTextField();
        txtPopUpUsuarioNombre = new javax.swing.JTextField();
        txtPopUpUsuarioApellidos = new javax.swing.JTextField();
        txtPopUpUsuarioTelefono = new javax.swing.JTextField();
        txtPopUpUsuarioEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnVaciarCamposUsuarios = new javax.swing.JButton();
        popUpInstalacion = new javax.swing.JFrame();
        txtPopUpInsNombre = new javax.swing.JTextField();
        txtPopUpInsPoblacion = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnPopUpInsEjecutar = new javax.swing.JButton();
        btnCancelarInstalacion = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtPopUpInsId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVaciarCamposInstalacion = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        adminModificarDatos = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        reservasListar = new javax.swing.JPanel();
        txtDiaListarReservas = new javax.swing.JTextField();
        txtMesListarReservas = new javax.swing.JTextField();
        txtAnioListarReservas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoraListarReservas = new javax.swing.JTextField();
        txtMinutoListarReservas = new javax.swing.JTextField();
        boxInstalacionListarReservas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDniListarReservas = new javax.swing.JTextField();
        btnListarReservas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        scrollPaneListarReservas = new javax.swing.JScrollPane();
        tablaListarReservas = new javax.swing.JTable();
        btnBorrarListarReservas = new javax.swing.JButton();
        btnNuevaListarReservas = new javax.swing.JButton();
        reservasNueva = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuariosNuevaReserva = new javax.swing.JTable();
        datePickNuevaReserva = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boxInstalacionesNuevaReserva = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDniNuevaReserva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNombreNuevaReserva = new javax.swing.JTextField();
        txtApellidosNuevaReserva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarUsuarioNuevaReserva = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaHorasDisponibles = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boxListaHoras = new javax.swing.JComboBox<>();
        btnReservarNuevaReserva = new javax.swing.JButton();
        reservasInforme = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usuariosListar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtDniVerUsuarios = new javax.swing.JTextField();
        txtNombreVerUsuarios = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtApellidosVerUsuarios = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTelefonoVerUsuarios = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnListarVerUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVerUsuarios = new javax.swing.JTable();
        btnBorrarUsuarioVerUsuarios = new javax.swing.JButton();
        btnEditarUsuarioVerUsuarios = new javax.swing.JButton();
        btnNuevoUsuarioVerUsuarios = new javax.swing.JButton();
        instalacionesListar = new javax.swing.JPanel();
        txtListarInstalacionesNombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtListarInstalacionesPoblacion = new javax.swing.JTextField();
        btnBuscarInstalaciones = new javax.swing.JButton();
        btnListarInstalacionesBorrar = new javax.swing.JButton();
        btnListarInstalacionesEditar = new javax.swing.JButton();
        btnListarInstalacionesNueva = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaListarInstalaciones = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        topMenuAdministrador = new javax.swing.JMenu();
        subMenuEditarAdmin = new javax.swing.JMenuItem();
        subMenuLogoutAdmin = new javax.swing.JMenuItem();
        separatorAdmin1 = new javax.swing.JPopupMenu.Separator();
        subMenuSalirAdmin = new javax.swing.JMenuItem();
        topMenuReservas = new javax.swing.JMenu();
        subMenuReservasVer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuReservasNueva = new javax.swing.JMenuItem();
        subMenuReservasPeriodica = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenuReservasSemanal = new javax.swing.JMenuItem();
        topMenuUsuarios = new javax.swing.JMenu();
        subMenuUsuariosListar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        subMenuUsuariosNuevo = new javax.swing.JMenuItem();
        topMenuInstalaciones = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        popUpUsuario.setTitle("Añadir / Editar Usuario");
        popUpUsuario.setMinimumSize(new java.awt.Dimension(600, 300));
        popUpUsuario.setName("popUpUsuario"); // NOI18N

        btnPopUpUsuarioEjecutar.setText("Añadir usuario");
        btnPopUpUsuarioEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopUpUsuarioEjecutarActionPerformed(evt);
            }
        });

        btnCancelarUsuario.setText("Cancelar");
        btnCancelarUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnCancelarUsuarioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUsuarioActionPerformed(evt);
            }
        });

        jLabel20.setText("DNI:");

        jLabel21.setText("Nombre:");

        jLabel22.setText("Apellidos");

        jLabel23.setText("Teléfono");

        jLabel24.setText("e-Mail");

        btnVaciarCamposUsuarios.setText("Vaciar Campos");
        btnVaciarCamposUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCamposUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popUpUsuarioLayout = new javax.swing.GroupLayout(popUpUsuario.getContentPane());
        popUpUsuario.getContentPane().setLayout(popUpUsuarioLayout);
        popUpUsuarioLayout.setHorizontalGroup(
            popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popUpUsuarioLayout.createSequentialGroup()
                        .addComponent(btnCancelarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnVaciarCamposUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPopUpUsuarioEjecutar))
                    .addGroup(popUpUsuarioLayout.createSequentialGroup()
                        .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(43, 43, 43)
                        .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPopUpUsuarioDni)
                            .addComponent(txtPopUpUsuarioNombre)
                            .addComponent(txtPopUpUsuarioApellidos)
                            .addComponent(txtPopUpUsuarioTelefono)
                            .addComponent(txtPopUpUsuarioEmail))))
                .addContainerGap())
        );
        popUpUsuarioLayout.setVerticalGroup(
            popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popUpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpUsuarioDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpUsuarioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpUsuarioTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(popUpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPopUpUsuarioEjecutar)
                    .addComponent(btnCancelarUsuario)
                    .addComponent(btnVaciarCamposUsuarios))
                .addContainerGap())
        );

        popUpInstalacion.setTitle("Añadir / Editar Instalación");
        popUpInstalacion.setMinimumSize(new java.awt.Dimension(600, 300));

        jTextField8.setText("16:00");
        jTextField8.setEnabled(false);

        jTextField9.setText("22:00");
        jTextField9.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        btnPopUpInsEjecutar.setText("Añadir nueva instalación");
        btnPopUpInsEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopUpInsEjecutarActionPerformed(evt);
            }
        });

        btnCancelarInstalacion.setText("Cancelar");
        btnCancelarInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInstalacionActionPerformed(evt);
            }
        });

        jLabel25.setText("Mes de cierre");

        jLabel26.setText("Hora de cierre");

        jLabel27.setText("Hora apertura");

        jLabel28.setText("Población");

        jLabel29.setText("Nombre");

        txtPopUpInsId.setEnabled(false);

        jLabel4.setText("ID");

        btnVaciarCamposInstalacion.setText("Vaciar Campos");
        btnVaciarCamposInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCamposInstalacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popUpInstalacionLayout = new javax.swing.GroupLayout(popUpInstalacion.getContentPane());
        popUpInstalacion.getContentPane().setLayout(popUpInstalacionLayout);
        popUpInstalacionLayout.setHorizontalGroup(
            popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popUpInstalacionLayout.createSequentialGroup()
                        .addComponent(btnCancelarInstalacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVaciarCamposInstalacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPopUpInsEjecutar))
                    .addGroup(popUpInstalacionLayout.createSequentialGroup()
                        .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPopUpInsPoblacion)
                            .addComponent(txtPopUpInsNombre)
                            .addGroup(popUpInstalacionLayout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(popUpInstalacionLayout.createSequentialGroup()
                                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPopUpInsId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        popUpInstalacionLayout.setVerticalGroup(
            popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpInsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpInsNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUpInsPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(popUpInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPopUpInsEjecutar)
                    .addComponent(btnCancelarInstalacion)
                    .addComponent(btnVaciarCamposInstalacion))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel30.setFont(new java.awt.Font("FreeSerif", 1, 36)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Gestión de Instalaciones Deportivas");

        jLabel1.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesión - Administrador");

        jTextField10.setFont(new java.awt.Font("DejaVu Sans", 2, 10)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Contraseña");
        jTextField10.setEnabled(false);

        jTextField11.setFont(new java.awt.Font("DejaVu Sans", 2, 10)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Usuario");
        jTextField11.setEnabled(false);

        jButton5.setText("Acceder");
        jButton5.setEnabled(false);

        javax.swing.GroupLayout adminModificarDatosLayout = new javax.swing.GroupLayout(adminModificarDatos);
        adminModificarDatos.setLayout(adminModificarDatosLayout);
        adminModificarDatosLayout.setHorizontalGroup(
            adminModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminModificarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(adminModificarDatosLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(adminModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField10)
                    .addComponent(jTextField11)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminModificarDatosLayout.setVerticalGroup(
            adminModificarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminModificarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        mainPanel.add(adminModificarDatos, "adminModificarDatos");

        txtDiaListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaListarReservasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("Fecha (DD/MM/AAAA)");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Hora (HH:MM)");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Instalación Deportiva");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("DNI");

        btnListarReservas.setText("Ver Reservas");
        btnListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarReservasActionPerformed(evt);
            }
        });

        tablaListarReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº Reserva", "Instalación", "Usuario", "Fecha", "Hora"
            }
        ));
        scrollPaneListarReservas.setViewportView(tablaListarReservas);

        btnBorrarListarReservas.setText("Borrar reserva seleccionada");
        btnBorrarListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarListarReservasActionPerformed(evt);
            }
        });

        btnNuevaListarReservas.setText("Añadir reserva");
        btnNuevaListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaListarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservasListarLayout = new javax.swing.GroupLayout(reservasListar);
        reservasListar.setLayout(reservasListarLayout);
        reservasListarLayout.setHorizontalGroup(
            reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(reservasListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneListarReservas)
                    .addGroup(reservasListarLayout.createSequentialGroup()
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(reservasListarLayout.createSequentialGroup()
                                .addComponent(txtDiaListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMesListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnioListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservasListarLayout.createSequentialGroup()
                                .addComponent(txtHoraListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinutoListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(boxInstalacionListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDniListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnListarReservas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservasListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevaListarReservas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarListarReservas)))
                .addContainerGap())
        );
        reservasListarLayout.setVerticalGroup(
            reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnListarReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(reservasListarLayout.createSequentialGroup()
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMesListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnioListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMinutoListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxInstalacionListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDniListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneListarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarListarReservas)
                    .addComponent(btnNuevaListarReservas))
                .addContainerGap())
        );

        mainPanel.add(reservasListar, "reservasListar");

        tablaUsuariosNuevaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaUsuariosNuevaReserva);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Fecha de la reserva");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setText("Instalación a reservar");

        boxInstalacionesNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxInstalacionesNuevaReservaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel11.setText("Usuario de la reserva");

        jLabel12.setText("DNI");

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellidos");

        btnBuscarUsuarioNuevaReserva.setText("Buscar");
        btnBuscarUsuarioNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioNuevaReservaActionPerformed(evt);
            }
        });

        tablaHorasDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Hora de reserva", "Titular de la reserva"
            }
        ));
        jScrollPane3.setViewportView(tablaHorasDisponibles);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel15.setText("Horario de la instalación y Horas disponibles");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Seleccione hora a reservar");

        boxListaHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00", "22:00:00" }));

        btnReservarNuevaReserva.setText("Añadir Reserva");
        btnReservarNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarNuevaReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservasNuevaLayout = new javax.swing.GroupLayout(reservasNueva);
        reservasNueva.setLayout(reservasNuevaLayout);
        reservasNuevaLayout.setHorizontalGroup(
            reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasNuevaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(datePickNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(reservasNuevaLayout.createSequentialGroup()
                        .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(reservasNuevaLayout.createSequentialGroup()
                                .addComponent(txtApellidosNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarUsuarioNuevaReserva))))
                    .addComponent(jLabel9)
                    .addComponent(boxListaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(boxInstalacionesNuevaReserva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(btnReservarNuevaReserva, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        reservasNuevaLayout.setVerticalGroup(
            reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasNuevaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservasNuevaLayout.createSequentialGroup()
                        .addComponent(boxInstalacionesNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datePickNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxListaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservasNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarUsuarioNuevaReserva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservarNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(reservasNueva, "reservasNueva");

        jLabel5.setText("Generar Informe de Reservas");

        javax.swing.GroupLayout reservasInformeLayout = new javax.swing.GroupLayout(reservasInforme);
        reservasInforme.setLayout(reservasInformeLayout);
        reservasInformeLayout.setHorizontalGroup(
            reservasInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(816, Short.MAX_VALUE))
        );
        reservasInformeLayout.setVerticalGroup(
            reservasInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(556, Short.MAX_VALUE))
        );

        mainPanel.add(reservasInforme, "reservasInforme");

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel16.setText("DNI de usuario");

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel18.setText("Apellidos");

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel19.setText("Teléfono");

        btnListarVerUsuarios.setText("Ver usuarios");
        btnListarVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVerUsuariosActionPerformed(evt);
            }
        });

        tablaVerUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Teléfono", "Correo electrónico"
            }
        ));
        jScrollPane1.setViewportView(tablaVerUsuarios);

        btnBorrarUsuarioVerUsuarios.setText("Borrar usuario seleccionado");
        btnBorrarUsuarioVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsuarioVerUsuariosActionPerformed(evt);
            }
        });

        btnEditarUsuarioVerUsuarios.setText("Editar usuario seleccionado");
        btnEditarUsuarioVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioVerUsuariosActionPerformed(evt);
            }
        });

        btnNuevoUsuarioVerUsuarios.setText("Añadir nuevo usuario");
        btnNuevoUsuarioVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioVerUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuariosListarLayout = new javax.swing.GroupLayout(usuariosListar);
        usuariosListar.setLayout(usuariosListarLayout);
        usuariosListarLayout.setHorizontalGroup(
            usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(usuariosListarLayout.createSequentialGroup()
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(75, 75, 75)
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(75, 75, 75)
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidosVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(75, 75, 75)
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtTelefonoVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnListarVerUsuarios))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevoUsuarioVerUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUsuarioVerUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarUsuarioVerUsuarios)))
                .addContainerGap())
        );
        usuariosListarLayout.setVerticalGroup(
            usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnListarVerUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usuariosListarLayout.createSequentialGroup()
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarUsuarioVerUsuarios)
                    .addComponent(btnEditarUsuarioVerUsuarios)
                    .addComponent(btnNuevoUsuarioVerUsuarios))
                .addContainerGap())
        );

        mainPanel.add(usuariosListar, "usuariosListar");

        txtListarInstalacionesNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListarInstalacionesNombreActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Búsqueda de Instalaciones Deportivas");

        jLabel32.setText("Nombre de la instalación");

        jLabel33.setText("Población");

        txtListarInstalacionesPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListarInstalacionesPoblacionActionPerformed(evt);
            }
        });

        btnBuscarInstalaciones.setText("Buscar instalaciones");
        btnBuscarInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInstalacionesActionPerformed(evt);
            }
        });

        btnListarInstalacionesBorrar.setText("Borrar instalación seleccionada");
        btnListarInstalacionesBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarInstalacionesBorrarActionPerformed(evt);
            }
        });

        btnListarInstalacionesEditar.setText("Editar instalación seleccionada");
        btnListarInstalacionesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarInstalacionesEditarActionPerformed(evt);
            }
        });

        btnListarInstalacionesNueva.setText("Añadir nueva instalación");
        btnListarInstalacionesNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarInstalacionesNuevaActionPerformed(evt);
            }
        });

        tablaListarInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaListarInstalaciones);

        javax.swing.GroupLayout instalacionesListarLayout = new javax.swing.GroupLayout(instalacionesListar);
        instalacionesListar.setLayout(instalacionesListarLayout);
        instalacionesListarLayout.setHorizontalGroup(
            instalacionesListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instalacionesListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instalacionesListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(instalacionesListarLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListarInstalacionesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListarInstalacionesPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnBuscarInstalaciones))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instalacionesListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListarInstalacionesNueva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarInstalacionesEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarInstalacionesBorrar)))
                .addContainerGap())
        );
        instalacionesListarLayout.setVerticalGroup(
            instalacionesListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instalacionesListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(instalacionesListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListarInstalacionesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(txtListarInstalacionesPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarInstalaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instalacionesListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarInstalacionesBorrar)
                    .addComponent(btnListarInstalacionesEditar)
                    .addComponent(btnListarInstalacionesNueva))
                .addContainerGap())
        );

        mainPanel.add(instalacionesListar, "instalacionesListar");

        getContentPane().add(mainPanel, "card7");

        topMenuAdministrador.setText("Administrador");
        topMenuAdministrador.setEnabled(false);
        topMenuAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topMenuAdministradorActionPerformed(evt);
            }
        });

        subMenuEditarAdmin.setText("Editar mis datos");
        subMenuEditarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuEditarAdminActionPerformed(evt);
            }
        });
        topMenuAdministrador.add(subMenuEditarAdmin);

        subMenuLogoutAdmin.setText("Cerrar sesión");
        topMenuAdministrador.add(subMenuLogoutAdmin);
        topMenuAdministrador.add(separatorAdmin1);

        subMenuSalirAdmin.setText("Salir");
        topMenuAdministrador.add(subMenuSalirAdmin);

        jMenuBar1.add(topMenuAdministrador);

        topMenuReservas.setText("Reservas");
        topMenuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topMenuReservasActionPerformed(evt);
            }
        });

        subMenuReservasVer.setText("Ver reservas");
        subMenuReservasVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReservasVerActionPerformed(evt);
            }
        });
        topMenuReservas.add(subMenuReservasVer);
        topMenuReservas.add(jSeparator1);

        subMenuReservasNueva.setText("Nueva reserva");
        subMenuReservasNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReservasNuevaActionPerformed(evt);
            }
        });
        topMenuReservas.add(subMenuReservasNueva);

        subMenuReservasPeriodica.setText("Nueva reserva periódica");
        subMenuReservasPeriodica.setEnabled(false);
        subMenuReservasPeriodica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReservasPeriodicaActionPerformed(evt);
            }
        });
        topMenuReservas.add(subMenuReservasPeriodica);
        topMenuReservas.add(jSeparator2);

        subMenuReservasSemanal.setText("Generar horario semanal");
        subMenuReservasSemanal.setEnabled(false);
        subMenuReservasSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuReservasSemanalActionPerformed(evt);
            }
        });
        topMenuReservas.add(subMenuReservasSemanal);

        jMenuBar1.add(topMenuReservas);

        topMenuUsuarios.setText("Usuarios");

        subMenuUsuariosListar.setText("Ver usuarios");
        subMenuUsuariosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuUsuariosListarActionPerformed(evt);
            }
        });
        topMenuUsuarios.add(subMenuUsuariosListar);
        topMenuUsuarios.add(jSeparator4);

        subMenuUsuariosNuevo.setText("Añadir usuario");
        subMenuUsuariosNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuUsuariosNuevoActionPerformed(evt);
            }
        });
        topMenuUsuarios.add(subMenuUsuariosNuevo);

        jMenuBar1.add(topMenuUsuarios);

        topMenuInstalaciones.setText("Instalaciones");

        jMenuItem3.setText("Ver instalaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        topMenuInstalaciones.add(jMenuItem3);
        topMenuInstalaciones.add(jSeparator5);

        jMenuItem4.setText("Nueva instalación");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        topMenuInstalaciones.add(jMenuItem4);

        jMenuBar1.add(topMenuInstalaciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void topMenuAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topMenuAdministradorActionPerformed

    }//GEN-LAST:event_topMenuAdministradorActionPerformed

    private void topMenuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topMenuReservasActionPerformed

    }//GEN-LAST:event_topMenuReservasActionPerformed

    private void subMenuEditarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuEditarAdminActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "adminModificarDatos");

    }//GEN-LAST:event_subMenuEditarAdminActionPerformed

    private void subMenuReservasVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReservasVerActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "reservasListar");
        llenarComboInstalaciones(boxInstalacionListarReservas, sesion);
    }//GEN-LAST:event_subMenuReservasVerActionPerformed

    private void subMenuReservasNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReservasNuevaActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "reservasNueva");
        llenarComboInstalaciones(boxInstalacionesNuevaReserva, sesion);
        datePickNuevaReserva.setDate(fechaActual);
        boxInstalacionesNuevaReserva.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                llenarTablaHoras(tablaHorasDisponibles, sesion, datePickNuevaReserva.getDate(), boxInstalacionesNuevaReserva.getSelectedItem().toString());
            }
        });
        datePickNuevaReserva.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                llenarTablaHoras(tablaHorasDisponibles, sesion, datePickNuevaReserva.getDate(), boxInstalacionesNuevaReserva.getSelectedItem().toString());
            }
        });
    }//GEN-LAST:event_subMenuReservasNuevaActionPerformed

    private void subMenuReservasPeriodicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReservasPeriodicaActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "reservasNuevaPeriodica");
    }//GEN-LAST:event_subMenuReservasPeriodicaActionPerformed

    private void subMenuReservasSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuReservasSemanalActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "reservasInforme");
    }//GEN-LAST:event_subMenuReservasSemanalActionPerformed

    private void txtDiaListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaListarReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaListarReservasActionPerformed

    private void btnListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarReservasActionPerformed
        listarReservas(txtDiaListarReservas, txtMesListarReservas, txtAnioListarReservas,
                txtHoraListarReservas, txtMinutoListarReservas, txtDniListarReservas,
                boxInstalacionListarReservas, tablaListarReservas, sesion);
    }//GEN-LAST:event_btnListarReservasActionPerformed

    private void btnBuscarUsuarioNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioNuevaReservaActionPerformed
        llenarTablaUsuarios(txtDniNuevaReserva, txtNombreNuevaReserva, txtApellidosNuevaReserva, tablaUsuariosNuevaReserva, sesion);
    }//GEN-LAST:event_btnBuscarUsuarioNuevaReservaActionPerformed

    private void boxInstalacionesNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxInstalacionesNuevaReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxInstalacionesNuevaReservaActionPerformed

    private void btnReservarNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarNuevaReservaActionPerformed
        try {
            String i = boxInstalacionesNuevaReserva.getSelectedItem().toString();
            String u = tablaUsuariosNuevaReserva.getValueAt(tablaUsuariosNuevaReserva.getSelectedRow(), 0).toString();
            //SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            //String fechaTexto = datePickNuevaReserva.getDate().toString();
            //System.out.println(fechaTexto);
            //Date f = formatoFecha.parse(fechaTexto);
            String h = boxListaHoras.getSelectedItem().toString();

            Date d = datePickNuevaReserva.getDate();
            java.sql.Date f = new java.sql.Date(d.getTime());

            crearReservaBD(i, u, f, h, sesion);
        } catch (ParseException pe) {
            System.out.println(pe.getMessage());
        }
    }//GEN-LAST:event_btnReservarNuevaReservaActionPerformed

    private void subMenuUsuariosNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuUsuariosNuevoActionPerformed
        popUpUsuario.setVisible(true);
        popUpUsuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_subMenuUsuariosNuevoActionPerformed

    private void subMenuUsuariosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuUsuariosListarActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "usuariosListar");
    }//GEN-LAST:event_subMenuUsuariosListarActionPerformed

    private void btnListarVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVerUsuariosActionPerformed
        llenarTablaUsuarios(txtDniVerUsuarios, txtNombreVerUsuarios, txtApellidosVerUsuarios, txtTelefonoVerUsuarios, tablaVerUsuarios, sesion);
    }//GEN-LAST:event_btnListarVerUsuariosActionPerformed

    private void btnCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioActionPerformed
        popUpUsuario.setVisible(false);
        btnVaciarCamposUsuariosActionPerformed(evt);
    }//GEN-LAST:event_btnCancelarUsuarioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        popUpInstalacion.setVisible(true);
        popUpInstalacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "instalacionesListar");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnNuevaListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaListarReservasActionPerformed
        subMenuReservasNuevaActionPerformed(evt);
    }//GEN-LAST:event_btnNuevaListarReservasActionPerformed

    private void btnNuevoUsuarioVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioVerUsuariosActionPerformed
        subMenuUsuariosNuevoActionPerformed(evt);
    }//GEN-LAST:event_btnNuevoUsuarioVerUsuariosActionPerformed

    private void btnPopUpUsuarioEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopUpUsuarioEjecutarActionPerformed
        try {
            insertarActualizarUsuario(txtPopUpUsuarioDni,txtPopUpUsuarioNombre,txtPopUpUsuarioApellidos,txtPopUpUsuarioEmail,txtPopUpUsuarioTelefono,sesion);
            JOptionPane.showMessageDialog(null, "Usuario insertado/actualizado con éxito.");            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnPopUpUsuarioEjecutarActionPerformed

    private void btnPopUpInsEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopUpInsEjecutarActionPerformed
        try {
            insertarActualizarInstalacion (txtPopUpInsId, txtPopUpInsNombre, txtPopUpInsPoblacion, sesion);
            JOptionPane.showMessageDialog(null, "Instalación añadida/editada con éxito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPopUpInsEjecutarActionPerformed

    private void btnEditarUsuarioVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioVerUsuariosActionPerformed
        try {
            enviarDatosUsuario(tablaVerUsuarios, sesion, txtPopUpUsuarioDni, txtPopUpUsuarioNombre, txtPopUpUsuarioApellidos, txtPopUpUsuarioTelefono, txtPopUpUsuarioEmail);
            popUpUsuario.setVisible(true);
            popUpUsuario.setLocationRelativeTo(null);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario primero.");
        }
    }//GEN-LAST:event_btnEditarUsuarioVerUsuariosActionPerformed

    private void btnBorrarUsuarioVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioVerUsuariosActionPerformed
        try {
            borrarUsuario(tablaVerUsuarios, sesion);
            JOptionPane.showMessageDialog(null, "Usuario borrado con éxito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarUsuarioVerUsuariosActionPerformed

    private void btnBorrarListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarListarReservasActionPerformed
        try {
            borrarReserva(tablaListarReservas, sesion);
            JOptionPane.showMessageDialog(null, "Reserva borrada con éxito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarListarReservasActionPerformed

    private void btnBuscarInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInstalacionesActionPerformed
        llenarTablaInstalaciones(txtListarInstalacionesNombre, txtListarInstalacionesPoblacion, tablaListarInstalaciones, sesion);
    }//GEN-LAST:event_btnBuscarInstalacionesActionPerformed

    private void btnListarInstalacionesNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarInstalacionesNuevaActionPerformed
        jMenuItem4ActionPerformed(evt);
    }//GEN-LAST:event_btnListarInstalacionesNuevaActionPerformed

    private void btnListarInstalacionesBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarInstalacionesBorrarActionPerformed
        try {
            borrarInstalacion(tablaListarInstalaciones, sesion);
            JOptionPane.showMessageDialog(null, "Instalación borrada con éxito.");
            btnBuscarInstalacionesActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnListarInstalacionesBorrarActionPerformed

    private void btnListarInstalacionesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarInstalacionesEditarActionPerformed
        try {
            enviarDatosInstalacion(tablaListarInstalaciones, sesion, txtPopUpInsId, txtPopUpInsNombre, txtPopUpInsPoblacion);
            popUpInstalacion.setVisible(true);
            popUpInstalacion.setLocationRelativeTo(null);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Seleccione una instalación primero.");
        }
    }//GEN-LAST:event_btnListarInstalacionesEditarActionPerformed

    private void btnVaciarCamposUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCamposUsuariosActionPerformed
        txtPopUpUsuarioDni.setText(null);
            txtPopUpUsuarioNombre.setText(null);
            txtPopUpUsuarioApellidos.setText(null);
            txtPopUpUsuarioEmail.setText(null);
            txtPopUpUsuarioTelefono.setText(null);
    }//GEN-LAST:event_btnVaciarCamposUsuariosActionPerformed

    private void btnCancelarUsuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarUsuarioAncestorAdded

    private void btnVaciarCamposInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCamposInstalacionActionPerformed
        txtPopUpInsId.setText(null);
        txtPopUpInsNombre.setText(null);
        txtPopUpInsPoblacion.setText(null);
    }//GEN-LAST:event_btnVaciarCamposInstalacionActionPerformed

    private void btnCancelarInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInstalacionActionPerformed
        btnVaciarCamposInstalacionActionPerformed(evt);
        popUpInstalacion.setVisible(false);
    }//GEN-LAST:event_btnCancelarInstalacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminModificarDatos;
    private javax.swing.JComboBox<String> boxInstalacionListarReservas;
    private javax.swing.JComboBox<String> boxInstalacionesNuevaReserva;
    private javax.swing.JComboBox<String> boxListaHoras;
    private javax.swing.JButton btnBorrarListarReservas;
    private javax.swing.JButton btnBorrarUsuarioVerUsuarios;
    private javax.swing.JButton btnBuscarInstalaciones;
    private javax.swing.JButton btnBuscarUsuarioNuevaReserva;
    private javax.swing.JButton btnCancelarInstalacion;
    private javax.swing.JButton btnCancelarUsuario;
    private javax.swing.JButton btnEditarUsuarioVerUsuarios;
    private javax.swing.JButton btnListarInstalacionesBorrar;
    private javax.swing.JButton btnListarInstalacionesEditar;
    private javax.swing.JButton btnListarInstalacionesNueva;
    private javax.swing.JButton btnListarReservas;
    private javax.swing.JButton btnListarVerUsuarios;
    private javax.swing.JButton btnNuevaListarReservas;
    private javax.swing.JButton btnNuevoUsuarioVerUsuarios;
    private javax.swing.JButton btnPopUpInsEjecutar;
    private javax.swing.JButton btnPopUpUsuarioEjecutar;
    private javax.swing.JButton btnReservarNuevaReserva;
    private javax.swing.JButton btnVaciarCamposInstalacion;
    private javax.swing.JButton btnVaciarCamposUsuarios;
    private com.toedter.calendar.JDateChooser datePickNuevaReserva;
    private javax.swing.JPanel instalacionesListar;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JFrame popUpInstalacion;
    private javax.swing.JFrame popUpUsuario;
    private javax.swing.JPanel reservasInforme;
    private javax.swing.JPanel reservasListar;
    private javax.swing.JPanel reservasNueva;
    private javax.swing.JScrollPane scrollPaneListarReservas;
    private javax.swing.JPopupMenu.Separator separatorAdmin1;
    private javax.swing.JMenuItem subMenuEditarAdmin;
    private javax.swing.JMenuItem subMenuLogoutAdmin;
    private javax.swing.JMenuItem subMenuReservasNueva;
    private javax.swing.JMenuItem subMenuReservasPeriodica;
    private javax.swing.JMenuItem subMenuReservasSemanal;
    private javax.swing.JMenuItem subMenuReservasVer;
    private javax.swing.JMenuItem subMenuSalirAdmin;
    private javax.swing.JMenuItem subMenuUsuariosListar;
    private javax.swing.JMenuItem subMenuUsuariosNuevo;
    private javax.swing.JTable tablaHorasDisponibles;
    private javax.swing.JTable tablaListarInstalaciones;
    private javax.swing.JTable tablaListarReservas;
    private javax.swing.JTable tablaUsuariosNuevaReserva;
    private javax.swing.JTable tablaVerUsuarios;
    private javax.swing.JMenu topMenuAdministrador;
    private javax.swing.JMenu topMenuInstalaciones;
    private javax.swing.JMenu topMenuReservas;
    private javax.swing.JMenu topMenuUsuarios;
    private javax.swing.JTextField txtAnioListarReservas;
    private javax.swing.JTextField txtApellidosNuevaReserva;
    private javax.swing.JTextField txtApellidosVerUsuarios;
    private javax.swing.JTextField txtDiaListarReservas;
    private javax.swing.JTextField txtDniListarReservas;
    private javax.swing.JTextField txtDniNuevaReserva;
    private javax.swing.JTextField txtDniVerUsuarios;
    private javax.swing.JTextField txtHoraListarReservas;
    private javax.swing.JTextField txtListarInstalacionesNombre;
    private javax.swing.JTextField txtListarInstalacionesPoblacion;
    private javax.swing.JTextField txtMesListarReservas;
    private javax.swing.JTextField txtMinutoListarReservas;
    private javax.swing.JTextField txtNombreNuevaReserva;
    private javax.swing.JTextField txtNombreVerUsuarios;
    private javax.swing.JTextField txtPopUpInsId;
    private javax.swing.JTextField txtPopUpInsNombre;
    private javax.swing.JTextField txtPopUpInsPoblacion;
    private javax.swing.JTextField txtPopUpUsuarioApellidos;
    private javax.swing.JTextField txtPopUpUsuarioDni;
    private javax.swing.JTextField txtPopUpUsuarioEmail;
    private javax.swing.JTextField txtPopUpUsuarioNombre;
    private javax.swing.JTextField txtPopUpUsuarioTelefono;
    private javax.swing.JTextField txtTelefonoVerUsuarios;
    private javax.swing.JPanel usuariosListar;
    // End of variables declaration//GEN-END:variables
}
