package instalaciones.entity;
// Generated 13-jun-2016 13:18:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instalaciones generated by hbm2java
 */
public class Instalaciones  implements java.io.Serializable {


     private Integer idInstalacion;
     private String nombre;
     private String poblacion;
     private Set reservases = new HashSet(0);

    public Instalaciones() {
    }

	
    public Instalaciones(String nombre) {
        this.nombre = nombre;
    }
    public Instalaciones(String nombre, String poblacion, Set reservases) {
       this.nombre = nombre;
       this.poblacion = poblacion;
       this.reservases = reservases;
    }
   
    public Integer getIdInstalacion() {
        return this.idInstalacion;
    }
    
    public void setIdInstalacion(Integer idInstalacion) {
        this.idInstalacion = idInstalacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


