package instalaciones.entity;
// Generated 13-jun-2016 13:18:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private Integer localizador;
     private Instalaciones instalaciones;
     private Usuarios usuarios;
     private Date fecha;
     private Date hora;

    public Reservas() {
    }

	
    public Reservas(Date fecha, Date hora) {
        this.fecha = fecha;
        this.hora = hora;
    }
    public Reservas(Instalaciones instalaciones, Usuarios usuarios, Date fecha, Date hora) {
       this.instalaciones = instalaciones;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(Integer localizador) {
        this.localizador = localizador;
    }
    public Instalaciones getInstalaciones() {
        return this.instalaciones;
    }
    
    public void setInstalaciones(Instalaciones instalaciones) {
        this.instalaciones = instalaciones;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


