package instalaciones.entity;
// Generated 13-jun-2016 13:18:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String dniUsuario;
     private String nombre;
     private String apellidos;
     private String email;
     private String telefono;
     private Set reservases = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String dniUsuario, String nombre, String telefono) {
        this.dniUsuario = dniUsuario;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    public Usuarios(String dniUsuario, String nombre, String apellidos, String email, String telefono, Set reservases) {
       this.dniUsuario = dniUsuario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.telefono = telefono;
       this.reservases = reservases;
    }
   
    public String getDniUsuario() {
        return this.dniUsuario;
    }
    
    public void setDniUsuario(String dniUsuario) {
        this.dniUsuario = dniUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


